on:
  push:
  schedule:
    - cron: '*/5 * * * *'  # Menjalankan setiap 5 menit
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: bcanseco/github-contribution-graph-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: admin@rerechanstore.eu.org
          MAX_DAYS: 365
          MIN_COMMITS_PER_DAY: 1
          MAX_COMMITS_PER_DAY: 5
